/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/reservations": {
    /** Get all reservations */
    get: operations["getReservations"];
    /** Create a new reservation */
    post: operations["createReservation"];
  };
  "/products": {
    /** Get all products */
    get: operations["getProducts"];
    /** Create a new product */
    post: operations["createProduct"];
  };
  "/customers": {
    /** Get all customers */
    get: operations["getCustomers"];
    /** Create a new customer */
    post: operations["createCustomer"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      id?: string;
      name?: string;
      /** @description either food or ticket */
      productType?: string;
      amount?: number;
      price?: number;
      /** @enum {string} */
      commmercialType?: "DONATION" | "SALE";
    };
    Reservation: {
      id?: string;
      name?: string;
      product?: components["schemas"]["Product"];
      amount?: number;
      requester?: components["schemas"]["Customer"];
      status?: components["schemas"]["ReservationStatus"];
    };
    ReservationStatus: {
      /** @enum {string} */
      status?: "PENDING" | "APPROVED" | "REJECTED";
      /** Format: date-time */
      timestamp?: string;
    };
    Customer: {
      id?: string;
      name?: string;
      customer?: unknown;
    };
    Receiver: {
      maxAmount?: number;
    };
    Donor: {
      paymentInformation?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get all reservations */
  getReservations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Reservation"][];
        };
      };
    };
  };
  /** Create a new reservation */
  createReservation: {
    /** @description Reservation to create */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Reservation"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Reservation"];
        };
      };
    };
  };
  /** Get all products */
  getProducts: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Product"][];
        };
      };
    };
  };
  /** Create a new product */
  createProduct: {
    /** @description Product to create */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Product"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
    };
  };
  /** Get all customers */
  getCustomers: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"][];
        };
      };
    };
  };
  /** Create a new customer */
  createCustomer: {
    /** @description Customer to create */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Customer"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
    };
  };
}
