/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      id?: string;
      name?: string;
      /** @description either food or ticket */
      productType?: string;
      amount?: number;
      price?: number;
      /** @enum {string} */
      commmercialType?: "DONATION" | "SALE";
    };
    Reservation: {
      id?: string;
      name?: string;
      product?: components["schemas"]["Product"];
      amount?: number;
      requester?: components["schemas"]["Customer"];
      status?: components["schemas"]["ReservationStatus"];
    };
    ReservationStatus: {
      /** @enum {string} */
      status?: "PENDING" | "APPROVED" | "REJECTED";
      /** Format: date-time */
      timestamp?: string;
    };
    Customer: {
      id?: string;
      name?: string;
      customer?: unknown;
    };
    Receiver: {
      maxAmount?: number;
    };
    Donor: {
      paymentInformation?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
